# Chapter 2 Lab

## Installing Packages

In [65]:
!pip install uv && uv pip install ISLP
import ISLP
print(ISLP.__version__)

Using Python 3.12.13 environment at: /usr
Checked 1 package in 121ms
0.4.1


## Basic Commands

In [66]:
# Function
print('fit a model with', 11, 'variables')

# Help
# print?

# Addition
print(15 + 1)

# Strings
string = "Hello" + " " + "World!"
print(string)

# Sequence: an ordered list
# 3 types of sequences: lists, tuples, and strings

# List: 'typical array'
x = [1, 2, 3]
print(x)

# Joining lists
y = [4, 5, 6]
print(x + y)

# Lists hold arbitrary objects and are added through concatination

fit a model with 11 variables
16
Hello World!
[1, 2, 3]
[1, 2, 3, 4, 5, 6]


## Numerical Python: numpy

In [67]:
# Importing numpy
# A package is a collection of modules that aren't always included in the base Python
import numpy as np

# In numpy, an array is a generic term for a multidimensional set of numbers
# np.array() defines 1D array, i.e. a vector

x = np.array([100, 200, 300])
y = np.array([20, 12, 17])

# Elements are added respectively, not concatination
# Vector math
print(x + y)

# Matrices are 2D arrays
# Matrices can also be created through np.matrix()
x = np.array([[1, 2], [3, 4]])
print(x)

# Attributes / associated objects
# Access by var.attribute
# numpy-specific
print(x.ndim)
print(x.dtype) # int64 - x is comprised of 64-bit integers

y = np.array([[1, 2], [3.0, 5.2]])
print(y.dtype) # now float64 - floating point numbers

# Package specific documentation
# np.array?

# Forcing data type
x = np.array([[1, 2], [3, 4]], dtype=float)
print(x)
print(x.dtype)

# Shape
print(x.shape)

# Methods
# Functions associated with an object

# Summing all elements
print(x.sum())

# Tuples can't be modified, lists can be modified
# Reshape the array: pass a tuple with new dimensions (rows, columns)
print('before')
print(x)
print('after')
x_reshape = x.reshape((1, 4))
print(x_reshape)

# Arrays are essentially a sequence of rows, row-major ordering
# The other way around is the column-major ordering

# Access (0-based indexing)
print(x[0, 1])
print(x[1, 1])

# Elements modified in x_reshape are also modified in x
# The two objects occupy the same space in memory
print(x)
print(x_reshape)
x_reshape[0][1] = 20
print(x)
print(x_reshape)

# Modifying a tuple throws an exception
tup = (2, 1, 10)
# tup[2] = 3

# x.shape - array dimensions in a tuple
# x.ndim - number of dimensions
# x.T - transpose
print(x.shape)
print(x.ndim)
print(x.T)

# Functions on arrays
x = np.sqrt(x) # Square root
print(x)
x = x**2 # Square elements
print(x)
print(x**0.5) # Square root, again

# Generating random data
# np.random.normal?
# loc - mean, scale - standard deviation

# Signatures, keywords, positional arguments
# Keywords substitued as in documentation - N(0, 1)
x = np.random.normal(size=50)
print(x)

# N(50, 1)
y = x + np.random.normal(50, 1, 50)
print(y)

# Correlation matrix
# np.corrcoef(x, y)
print(np.corrcoef(x, y))

# Setting a random seed
# rng has all random number generating methods in np.random
print(np.random.normal(scale = 5, size = 2))
print(np.random.normal(scale = 5, size = 2))

rng = np.random.default_rng(1303)
print(rng.normal(scale = 5, size = 2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale = 5, size = 2))

# np.mean(), np.var(), np.std()
rng = np.random.default_rng(3)
y = rng.standard_normal(10)

# Mean
print(np.mean(y), y.mean())
# Variartion, divides by the sample size n rather than n - 1
print(np.var(y), y.var(), np.mean((y - y.mean())**2))
# Standard Deviation
print(np.std(y), y.std())

# np.var?

# Works on matrices as well
X = rng.standard_normal((10, 3)) # N(0, 1)
print(X)
print(X.mean(axis=0)) # row-major ordering, column means
print(X.mean(axis=1)) # still row-major ordering, row means

[120 212 317]
[[1 2]
 [3 4]]
2
int64
float64
[[1. 2.]
 [3. 4.]]
float64
(2, 2)
10.0
before
[[1. 2.]
 [3. 4.]]
after
[[1. 2. 3. 4.]]
2.0
4.0
[[1. 2.]
 [3. 4.]]
[[1. 2. 3. 4.]]
[[ 1. 20.]
 [ 3.  4.]]
[[ 1. 20.  3.  4.]]
(2, 2)
2
[[ 1.  3.]
 [20.  4.]]
[[1.         4.47213595]
 [1.73205081 2.        ]]
[[ 1. 20.]
 [ 3.  4.]]
[[1.         4.47213595]
 [1.73205081 2.        ]]
[ 0.59085363  1.17300617 -0.41718037  0.6891423   1.02786595 -0.41687045
 -0.96150811  0.22622124 -0.01032019 -1.4204772  -0.44572303 -0.90741785
  1.67635274  1.32162869  0.19208923 -0.28632113 -0.2075917  -1.23392553
 -1.26813445  0.95363184 -0.11220429 -0.11194656 -1.10772218  0.16245682
  0.76548584  1.07427857  0.38331567 -0.75434694 -0.13175785  0.35053963
 -0.20331447  1.22946984  0.9645585   0.08611375  0.54832648  1.54116566
  0.02649425  0.97850985 -0.01299601  0.09021581  0.57515251  0.47200562
 -1.03696305  1.49360175  0.47229518  0.67789455  0.25882794  0.19334906
  1.8344333  -2.03057318]
[50.09504256 51